name: PR Build Gate

on:
  pull_request:
    branches:
      - '*'

jobs:
  build-lib:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/lib

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile
    - run: yarn build

  build-docs:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/docs

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile
    - run: yarn build